
CREATE DATABASE QLBATDONGSAN777;
USE QLBATDONGSAN777;

CREATE TABLE VANPHONG(
MaVP INT NOT NULL,
DiaDiem VARCHAR(255) NULL,
PRIMARY KEY(MaVP)
);

CREATE TABLE CHUSOHUU(
MaCSH INT NOT NULL,
HoTen VARCHAR(45) NULL,
DiaChi VARCHAR(45) NULL,
SoDT VARCHAR(45) NULL,
PRIMARY KEY(MaCSH)
);

CREATE TABLE BATDONGSAN(
MaBDS INT NOT NULL,
DiaChi VARCHAR(45) NULL,
MaVP INT NOT NULL,
MaCSH INT NOT NULL,
 PRIMARY KEY(MaBDS)

);

CREATE TABLE NHANVIEN(
MaNV INT NOT NULL,
HoTen VARCHAR(45) NULL,
Email VARCHAR(45) NULL,
SoDT INT NULL,
MaVP INT NOT NULL,
PRIMARY KEY(MaNV)
);

CREATE TABLE NHANTHAN(
MaNT INT NOT NULL,
HoTen VARCHAR(45) NULL,
NgaySinh DATE NULL,
MoiQuanHe VARCHAR(255)NULL,
MaNV INT NOT NULL,
PRIMARY KEY(MaNT)
);

CREATE TABLE QUANLY(
ID INT NOT NULL,
MaVP INT NOT NULL,
MaNV INT NOT NULL,
PRIMARY KEY(ID)
);

ALTER TABLE BATDONGSAN
ADD CONSTRAINT fk_BATDONGSAN_VANPHONG FOREIGN KEY(MaVP) REFERENCES VANPHONG(MaVP),
ADD CONSTRAINT fk_BDS_CSH FOREIGN KEY (MaCSH) REFERENCES CHUSOHUU(MaCSH);

ALTER TABLE NHANVIEN
ADD CONSTRAINT fk_NHANVIEN_VANPHONG FOREIGN KEY(MaVP) REFERENCES VANPHONG(MaVP) ON DELETE NO ACTION ON UPDATE NO ACTION;

ALTER TABLE NHANTHAN
ADD CONSTRAINT fk_NHANTHAN_NHANVIEN FOREIGN KEY(MaNV) REFERENCES NHANVIEN(MaNV);

ALTER TABLE QUANLY
ADD CONSTRAINT fk_QUANLY_VANPHONG FOREIGN KEY(MaVP) REFERENCES VANPHONG(MaVP),
ADD CONSTRAINT fk_QUANLY_NHANVIEN FOREIGN KEY (MaNV) REFERENCES NHANVIEN(MANV);